### ISSUE TITLE
Etherscan Links Open Inside Write Tab

### ISSUE THREAD

**Issue by wjmelements** [etherscan/writecontract#17]
Repro: For a proxy contract, such as TrueUSD, click on the link next to "Showing ABI for possible implementation".
Expected behavior: link opens in current browser tab.
Actual behavior: link opens inside Write Contract tab.

Screenshot:
<img width="1673" alt="screen shot 2019-01-26 at 4 28 24 pm" src="https://user-images.githubusercontent.com/799573/51794416-93791b80-2187-11e9-9470-1fc9f8a7e84a.png">

**Comment by wjmelements** [comment]
The same happens if you click the "Powered by Etherscan.io" link at the bottom.

**Comment by khairulmax** [comment]
fixed..thanks @wjmelements
