### ISSUE TITLE
Broken on Rinkeby

### ISSUE THREAD

**Issue by sshelton76** [etherscan/writecontract#18]
It appears this is broken on Rinkeby.
I have what amounts to a bog standard ERC20 contract here
```
https://rinkeby.etherscan.io/address/0x0a97190ea26f7e87566a972f8f0f6632274eb1b2
```

Source code has been verified and read contract is working, but write contract says...
```
 Sorry, we were unable to locate a matching Contract ABI or SourceCode for this contract.

If you are the contract owner, please Verify Your Contract Source Code here.
```

Not sure how relevant it is, but the "Verify Your Contract Source Code here" link is pointing to
```
https://etherscan.io/verifyContract2?a=0x0a97190ea26f7e87566a972f8f0f6632274eb1b2
```
Which is obviously wrong, so when I noticed I had landed there I went to 
```
https://rinkeby.etherscan.io/verifyContract2?a=0x0a97190ea26f7e87566a972f8f0f6632274eb1b2
```

Where I had no problems verifying.

I know it's just the rinkeby testnet, but if you could please fix the write contract functionality there I would be much obliged.  Thanks!

**Comment by sshelton76** [comment]
This appears to have been resolved, so I'll close the issue now.

**Comment by GCole64** [comment]
Thank you I am trying to get help I do not know how to code
