### ISSUE TITLE
Write Contract ABI not showing for Verified Contract on Testnets

### ISSUE THREAD

**Issue by wjmelements** [etherscan/writecontract#21]
Even though the contract is verified, the write contract ABI does not show.

Contract: https://rinkeby.etherscan.io/address/0xa39F6eB676588Ff6f7e755D0A30A08dce5aD68E1#writeContract

![Screen Shot 2019-03-18 at 8 27 18 PM](https://user-images.githubusercontent.com/799573/54578266-5c233000-49bc-11e9-9465-1b3038d95ead.png)

One reason this might be is that it was an implementation contract for a proxy, and I fetched the ABI from the proxy before verifying it in the implementation contract. It is possible that the result, "Sorry, we were unable to locate a matching Contract ABI or SourceCode for this contract.", was cached the first time and still continues to surface even though it was a 404. The fix is to not cache for 404s, and would not be implemented within this repository.

**Comment by wjmelements** [comment]
![Screen Shot 2019-03-18 at 8 27 03 PM](https://user-images.githubusercontent.com/799573/54578355-b4f2c880-49bc-11e9-91e1-54164c67f933.png)

**Comment by wjmelements** [comment]
The issue has resolved for this contract but it may still happen in the future. I still suspect it is a caching issue.

**Comment by wjmelements** [comment]
I have reproduced the issue while my connected metamask was set to mainnet but it works while I am set to Rinkeby. Updating the title.

**Comment by wjmelements** [comment]
![Screen Shot 2019-04-25 at 2 08 35 PM](https://user-images.githubusercontent.com/799573/56768584-a6d65b80-6763-11e9-97a1-b3edf77b2033.png)

**Comment by khairulmax** [comment]
issue fixed

**Comment by mo-bay** [comment]
I am experiencing the same problem, even tough the contract is verified 
![image](https://user-images.githubusercontent.com/40464904/124274203-a4dd6380-db49-11eb-8d11-fdd108a94dda.png)

The contract was deployed and verified via Remix IDE here are two GUID's : 
`
upnuax1eewanzpg8uk9b8ydkmzgc7kc73iwdkh2ayxkhq86kpm | Verified
myf9racjaguhccmxswlfwnkkytgq71vdm6prucyvmyfddmahvh | Verified
`
