### ISSUE TITLE
Not working with array pram

### ISSUE THREAD

**Issue by huahuayu** [etherscan/writecontract#3]
Hi please visit below address, executeBatchTransfer method has two params, both are dynamic array, after I give the param, say ["0x3de2f9592e532079594edeadaacd9299d6d1b00b","0x933391ab09ac2ffea4372d37cb96004079c0a9fd"], [1,1], and click write, nothing happend, metamask not triggered.
 
https://etherscan.io/address/0xf9f6382790d74646aa4d590594442523ca4ed159#writeContract

**Comment by khairulmax** [comment]
@huahuayu fixed. 

example
1. _dests (address[]) = 0x3de2f9592e532079594edeadaacd9299d6d1b00b, 0x933391ab09ac2ffea4372d37cb96004079c0a9fd
2. _values (uint256[]) = 1,1

**Comment by andrasfuchs** [comment]
I still have a problem with array parameters.

![image](https://user-images.githubusercontent.com/910321/43511322-65b4b7b8-9578-11e8-9b88-4ab98234e174.png)
