### ISSUE TITLE
Write to method without no params fails

### ISSUE THREAD

**Issue by roderik** [etherscan/writecontract#4]
There is an issue when trying to write to a function without any params.
Like: https://etherscan.io/address/0x8bf82372f60100399dc633581ef4a40366a98750#writeContract

The issue is on https://github.com/etherscan/writecontract/blob/master/writecontract.html#L290 where the error will become https://www.dropbox.com/s/c1s76cqjjg1mz2e/Screenshot%202018-07-25%2010.14.53.png?dl=0

**Comment by AllenChong** [comment]
issue

**Comment by mtbitcoin** [comment]
@khairulmax follow up and close please

**Comment by khairulmax** [comment]
@roderik please try again

**Comment by andrasfuchs** [comment]
Is this bug fixed now?

I have the same problem with my contract's parameterless write function. Clicking on the Write button it doesn't generate a transaction.

Example: 
https://rinkeby.etherscan.io/address/0x9b4c9ee37693f5cb4d0b854a67271bbe6e986a86#writeContract

function turnOffWhiteListing() public onlyOwner

Browser's error message:
![image](https://user-images.githubusercontent.com/910321/43510645-91f27862-9576-11e8-9a49-8f11835760d2.png)
