### ISSUE TITLE
Why web3 is not avaible with my account

### ISSUE THREAD

**Issue by gulabritoly** [etherscan/writecontract#40]
I want to transfer my coin but sowing  web3 provider is not avaible. Then how can I connect my account with web3

**Comment by Enigmatic331** [comment]
Hey @gulabritoly,

Assuming you have Metamask installed and your wallet initialised, likely you'd need to check if the site is allowed to connect to your Web3 provider (in this case Metamask).

Something similar to the below:

![image](https://user-images.githubusercontent.com/28551011/67732475-66b7a480-fa36-11e9-9a16-41890e149d52.png)
