### ISSUE TITLE
Can't read public view API in KyberNetwork contract

### ISSUE THREAD

**Issue by ilanDoron** [etherscan/writecontract#51]
contract:

https://ropsten.etherscan.io/address/0x9ec49c41fdc4c79fdb042af37659f2e3220ad0a4#readContract

API:
4. getContracts.

ABI:

{
      "inputs": [],
      "name": "getContracts",
      "outputs": [
        {
          "internalType": "contract IKyberFeeHandler",
          "name": "kyberFeeHandlerAddress",
          "type": "address"
        },
        {
          "internalType": "contract IKyberDao",
          "name": "kyberDaoAddress",
          "type": "address"
        },
        {
          "internalType": "contract IKyberMatchingEngine",
          "name": "kyberMatchingEngineAddress",
          "type": "address"
        },
        {
          "internalType": "contract IKyberStorage",
          "name": "kyberStorageAddress",
          "type": "address"
        },
        {
          "internalType": "contract IGasHelper",
          "name": "gasHelperAddress",
          "type": "address"
        },
        {
          "internalType": "contract IKyberNetworkProxy[]",
          "name": "kyberProxyAddresses",
          "type": "address[]"
        }
      ],
      "stateMutability": "view",
      "type": "function"
    }

**Comment by wchuan11** [comment]
Issue is resolved.
![image](https://user-images.githubusercontent.com/467814/88047928-fe40c280-cb84-11ea-948a-55b2dda02d86.png)
