### ISSUE TITLE
String values are percent encoded

### ISSUE THREAD

**Issue by fulldecent** [etherscan/writecontract#6]
Transaction

https://etherscan.io/tx/0x7584c60cf96e557b077285bfef8d8199f13b0ddaf47e3bc2700d0b4320e58a95

Input values

![screen shot 2018-08-03 at 4 37 50 pm](https://user-images.githubusercontent.com/382183/43664656-a885bc8a-973b-11e8-8e32-9074d0d8322e.png)

What hit the blockchain

![screen shot 2018-08-03 at 4 38 47 pm](https://user-images.githubusercontent.com/382183/43664679-bc22df84-973b-11e8-9c1e-5c906eb82d47.png)

**Comment by khairulmax** [comment]
@fulldecent please try again
