### ISSUE TITLE
Cant sell SAFEMOON on FDN Fantom Sushiswap. Give unknown error

### ISSUE THREAD

**Issue by vinilpat** [etherscan/writecontract#70]
I am trying to sell SAFEMOON (crontract id: 0x7777a9c298d347498375e57ca8e8f919428ffa37) using sushiswap. however I can unable to sell the tokens and gives me an unknown error. Can you please help to check this and solve for people to buy and sell please?

**Comment by emadami** [comment]
> I am trying to sell SAFEMOON (crontract id: 0x7777a9c298d347498375e57ca8e8f919428ffa37) using sushiswap. however I can unable to sell the tokens and gives me an unknown error. Can you please help to check this and solve for people to buy and sell please?

**Comment by 1hi1ok** [comment]
Hello

**Comment by 1hi1ok** [comment]
BNB

**Comment by emadami** [comment]
25800

در تاریخ شنبه ۲۲ مهٔ ۲۰۲۱،‏ ۵:۰۷ 1hi1ok ***@***.***> نوشت:

**Comment by 1hi1ok** [comment]
Hello

**Comment by emadami3060** [comment]
Hi

**Comment by 1hi1ok** [comment]
ETH

**Comment by bdhaccess94** [comment]
hey, that contract is supposedly me as the owner, im trying to claim rights to it. r u guys using it as part of the project to help me get my funds back, cuz that i will pay well for once the projects complete to whover can help me with this. i just dont know a lat about programming and such and am trying to get the recovery phrase.

**Comment by 1hi1ok** [comment]
Hello

**Comment by bdhaccess94** [comment]
hi :)

**Comment by bdhaccess94** [comment]
> I am trying to sell SAFEMOON (crontract id: 0x7777a9c298d347498375e57ca8e8f919428ffa37) using sushiswap. however I can unable to sell the tokens and gives me an unknown error. Can you please help to check this and solve for people to buy and sell please?

theres been errors with this for a long time...i cant make transactions anywhere and people dont get the token on the recieving end.

**Comment by 1hi1ok** [comment]
Seefmoon

**Comment by 1hi1ok** [comment]
> Seefmoon

**Comment by bdhaccess94** [comment]
> > I am trying to sell SAFEMOON (crontract id: 0x7777a9c298d347498375e57ca8e8f919428ffa37) using sushiswap. however I can unable to sell the tokens and gives me an unknown error. Can you please help to check this and solve for people to buy and sell please?
> 
> theres been errors with this for a long time...i cant make transactions anywhere and people dont get the token on the recieving end.

however insta dapp does form transactions in a test enviroment then sends them to tenderly but idk much about test transactions.
